#!/bin/sh
#
# @name Gazebo ARM_HEX
#
# @type Hexarotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=arm_hex}

param set-default MAV_TYPE 13
param set-default MIS_TAKEOFF_ALT 1.0

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 0.34
param set-default CA_ROTOR0_KM  -0.05

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -0.34
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.3
param set-default CA_ROTOR2_PY -0.17
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.3
param set-default CA_ROTOR3_PY 0.17
param set-default CA_ROTOR3_KM 0.05

param set-default CA_ROTOR4_PX 0.3
param set-default CA_ROTOR4_PY 0.17
param set-default CA_ROTOR4_KM 0.05

param set-default CA_ROTOR5_PX -0.3
param set-default CA_ROTOR5_PY -0.17
param set-default CA_ROTOR5_KM -0.05

param set-default SIM_GZ_EN 1

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 100
param set-default SIM_GZ_EC_MIN2 100
param set-default SIM_GZ_EC_MIN3 100
param set-default SIM_GZ_EC_MIN4 100
param set-default SIM_GZ_EC_MIN5 100
param set-default SIM_GZ_EC_MIN6 100

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000

param set-default COM_RCL_EXCEPT 7
param set-default COM_RC_IN_MODE 1
