#!/bin/sh
#
# @name Gazebo ARM_HEX
#
# @type Hexarotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=arm_mark1}

param set-default MAV_TYPE 13
param set-default MIS_TAKEOFF_ALT 1.0

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 0.34
param set-default CA_ROTOR0_KM  -0.0135
param set-default CA_ROTOR0_CT  1.0
param set-default CA_ROTOR0_AX -0.731350463179516
param set-default CA_ROTOR0_AY 0.0
param set-default CA_ROTOR0_AZ -0.682001832842032


param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -0.34
param set-default CA_ROTOR1_KM  0.0135
param set-default CA_ROTOR1_CT  1.0
param set-default CA_ROTOR1_AX -0.731350463179516
param set-default CA_ROTOR1_AY 0.0
param set-default CA_ROTOR1_AZ -0.682001832842032

param set-default CA_ROTOR2_PX 0.2944
param set-default CA_ROTOR2_PY -0.17
param set-default CA_ROTOR2_KM -0.0135
param set-default CA_ROTOR2_CT  1.0
param set-default CA_ROTOR2_AX 0.365676007088906
param set-default CA_ROTOR2_AY 0.633367632453399
param set-default CA_ROTOR2_AZ -0.682001832842032

param set-default CA_ROTOR3_PX -0.2944
param set-default CA_ROTOR3_PY 0.17
param set-default CA_ROTOR3_KM 0.0135
param set-default CA_ROTOR3_CT  1.0
param set-default CA_ROTOR3_AX 0.365676007088906
param set-default CA_ROTOR3_AY 0.633367632453399
param set-default CA_ROTOR3_AZ -0.682001832842032

param set-default CA_ROTOR4_PX 0.2944
param set-default CA_ROTOR4_PY 0.17
param set-default CA_ROTOR4_KM 0.0135
param set-default CA_ROTOR4_CT  1.0
param set-default CA_ROTOR4_AX 0.365676007088906
param set-default CA_ROTOR4_AY -0.633367632453399
param set-default CA_ROTOR4_AZ -0.682001832842032

param set-default CA_ROTOR5_PX -0.2944
param set-default CA_ROTOR5_PY -0.17
param set-default CA_ROTOR5_KM -0.0135
param set-default CA_ROTOR5_CT  1.0
param set-default CA_ROTOR5_AX 0.365676007088906
param set-default CA_ROTOR5_AY -0.633367632453399
param set-default CA_ROTOR5_AZ -0.682001832842032

param set-default SIM_GZ_EN 1

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 1
param set-default SIM_GZ_EC_MIN2 1
param set-default SIM_GZ_EC_MIN3 1
param set-default SIM_GZ_EC_MIN4 1
param set-default SIM_GZ_EC_MIN5 1
param set-default SIM_GZ_EC_MIN6 1

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000

param set-default CA_METHOD 0

param set-default COM_RCL_EXCEPT 7
param set-default COM_RC_IN_MODE 1

param set-default THR_MDL_FAC 1.0
param set-default HTE_THR_RANGE 0.4
param set-default MPC_THR_HOVER 0.6
param set-default MPC_THR_MIN 0.05

param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_I 0.0
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_I 0.0
param set-default MC_YAWRATE_D 0.0
param set-default MC_YAWRATE_I 0.0

param set-default MC_PR_INT_LIM 0.0
param set-default MC_RR_INT_LIM 0.0
param set-default MC_YR_INT_LIM 0.0

param set-default MC_YAWRATE_P 0.1
param set-default MC_YAW_P 2
