#!/bin/sh
#
# @name Gazebo ARM_HEX
#
# @type Hexarotor
# @class Copter

. ${R}etc/init.d/rc.mc_defaults


param set MAV_TYPE 13
param set MIS_TAKEOFF_ALT 3.0

param set CA_AIRFRAME 0
param set CA_ROTOR_COUNT 6

param set CA_ROTOR0_PX 0.0
param set CA_ROTOR0_PY 0.34
param set CA_ROTOR0_KM -0.00828498
param set CA_ROTOR0_CT 1.0

param set CA_ROTOR1_PX 0.0
param set CA_ROTOR1_PY -0.34
param set CA_ROTOR1_KM 0.00828498
param set CA_ROTOR1_CT 1.0

param set CA_ROTOR2_PX 0.3
param set CA_ROTOR2_PY -0.17
param set CA_ROTOR2_KM -0.00828498
param set CA_ROTOR2_CT 1.0

param set CA_ROTOR3_PX -0.3
param set CA_ROTOR3_PY 0.17
param set CA_ROTOR3_KM 0.00828498
param set CA_ROTOR3_CT 1.0

param set CA_ROTOR4_PX 0.3
param set CA_ROTOR4_PY 0.17
param set CA_ROTOR4_KM 0.00828498
param set CA_ROTOR4_CT 1.0

param set CA_ROTOR5_PX -0.3
param set CA_ROTOR5_PY -0.17
param set CA_ROTOR5_KM -0.00828498
param set CA_ROTOR5_CT 1.0

param set CA_METHOD 0

param set COM_RCL_EXCEPT 7
param set COM_RC_IN_MODE 1

param set THR_MDL_FAC 1.0
param set HTE_THR_RANGE 0.4
param set MPC_THR_HOVER 0.6
param set MPC_THR_MIN 0.05

param set MC_PITCHRATE_D 0.0
param set MC_PITCHRATE_I 0.0
param set MC_ROLLRATE_D 0.0
param set MC_ROLLRATE_I 0.0
param set MC_YAWRATE_D 0.0
param set MC_YAWRATE_I 0.0

param set MC_PR_INT_LIM 0.0
param set MC_RR_INT_LIM 0.0
param set MC_YR_INT_LIM 0.0

param set MC_YAWRATE_P 0.1
param set MC_YAW_P 2











param set BAT1_SOURCE 1
param set BAT2_R_INTERNAL 0.004999999888241291

param set CAL_BARO0_ID 0
param set CAL_BARO1_ID 0

param set COM_ARM_BAT_MIN 0.0
param set COM_DISARM_LAND -1.0
param set COM_DISARM_MAN 0
param set COM_DISARM_PRFLT 0.0
param set COM_RC_OVERRIDE 3

param set EKF2_DELAY_MAX 300.0
param set EKF2_EV_CTRL 11
param set EKF2_EV_DELAY 300.0
param set EKF2_EV_POS_Z 0.019999999552965164
param set EKF2_GPS_CHECK 245
param set EKF2_GPS_CTRL 0
param set EKF2_HGT_REF 3
param set EKF2_MAG_DECL 3.137201070785522461
param set EKF2_OF_POS_X -0.107500001788139343
param set EKF2_RNG_A_HMAX 10.0
param set EKF2_RNG_QLTY_T 0.20000000298023224

param set HTE_THR_RANGE 0.20000000298023224
param set MIS_TAKEOFF_ALT 1.5

param set MAV_0_CONFIG 1000
param set MAV_1_CONFIG 1000
param set MAV_1_MODE 2
param set MAV_2_CONFIG 0
param set MAV_2_MODE 2
param set MAV_2_REMOTE_PRT 14540
param set MAV_2_UDP_PRT 14540



param set MPC_TKO_SPEED 1.0

param set PWM_MAIN_FUNC1 101
param set PWM_MAIN_FUNC2 102
param set PWM_MAIN_FUNC3 103
param set PWM_MAIN_FUNC4 104
param set PWM_MAIN_FUNC5 105
param set PWM_MAIN_FUNC6 106

param set PWM_MAIN_MAX1 1900
param set PWM_MAIN_MAX2 1900
param set PWM_MAIN_MAX3 1900
param set PWM_MAIN_MAX4 1900
param set PWM_MAIN_MAX5 1900
param set PWM_MAIN_MAX6 1900

param set PWM_MAIN_MIN1 1100
param set PWM_MAIN_MIN2 1100
param set PWM_MAIN_MIN3 1100
param set PWM_MAIN_MIN4 1100
param set PWM_MAIN_MIN5 1100
param set PWM_MAIN_MIN6 1100

param set PWM_AUX_MAX1 1900
param set PWM_AUX_MAX2 1900
param set PWM_AUX_MAX3 1900
param set PWM_AUX_MAX4 1900
param set PWM_AUX_MAX5 1900
param set PWM_AUX_MAX6 1900

param set PWM_AUX_MIN1 1100
param set PWM_AUX_MIN2 1100
param set PWM_AUX_MIN3 1100
param set PWM_AUX_MIN4 1100
param set PWM_AUX_MIN5 1100
param set PWM_AUX_MIN6 1100

param set SENS_BOARD_X_OFF 0.8392560482025146
param set SENS_BOARD_Y_OFF -0.7872895002365112

param set SYS_AUTOSTART 6500


param set UAVCAN_SUB_FLOW 1
param set UAVCAN_SUB_RNG 1